- alias: 'input_daily_reset'

  trigger:
    platform: time
    after: "02:00"

  condition:
    condition: state
    entity_id: input_boolean.enable_guest
    state: 'off'

  action:
    service: homeassistant.turn_on
    entity_id: scene.input_reset
