- alias: 'input_normal'

  trigger:
    platform: state
    entity_id: input_boolean.bedtime_normal
    state: 'on'

  action:
    service: homeassistant.turn_on
    entity_id: scene.input_normal_bedtime
