- alias: lights_full_outside
  initial_state: True

  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00:00'

  - platform: time
    at: "06:00:00"

  - platform: event
    event_type: telegram_command
    event_data:
      command: '/outside'

  action:
    service: light.hue_activate_scene
    data:
      group_name: "Outside"
      scene_name: "Full"

########################

- alias: lights_dim_outside
  initial_state: True

  trigger:
  - platform: time
    at: '22:30:00'

  action:
    service: light.hue_activate_scene
    data:
      group_name: "Outside"
      scene_name: "Dim"

########################

- alias: lights_off_outside
  initial_state: True

  trigger:
  - platform: time
    at: "23:00:00"

  - platform: sun
    event: sunrise
    offset: '1:00:00'

  - platform: time
    at: '08:30:00'

  action:
  - service: scene.turn_on
    entity_id: scene.hue_outside_off
