- alias: lights_off_morning_inside
  id: lights_off_morning_inside
  initial_state: True

  trigger:
  - platform: time
    at: '08:45:00'

  condition:
  - condition: state
    entity_id: input_boolean.disable_work
    state: 'off'
  - condition: state
    entity_id: input_boolean.enable_guest
    state: 'off'
  - condition: state
    entity_id: input_boolean.working_from_home
    state: 'off'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'

  action:
    service: homeassistant.turn_off
    entity_id: light.living_room
    data:
      transition: 2

########################

- alias: lights_off_bedtime_inside
  id: lights_off_bedtime_inside
  initial_state: True

  trigger:
  - platform: time
    at: '22:15:00'

  condition:
  - condition: state
    entity_id: input_boolean.disable_bedtime
    state: 'off'
  - condition: state
    entity_id: input_boolean.enable_guest
    state: 'off'
  - condition: state
    entity_id: media_player.media_centre
    state: 'off'

  action:
    service: homeassistant.turn_off
    entity_id: light.living_room
    data:
      transition: 2
