- alias: lights_on_morning_inside
  id: lights_on_morning_inside
  initial_state: True

  trigger:
  - platform: time
    at: '05:55:00'
    # Triggers at 5.55 am
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/dim'
      # Type "/dim" in the no.33 bot

  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Dim"
      # Activates native Hue scene 'Dim'

########################

- alias: lights_on_sunset_inside
  id: lights_on_sunset_inside
  initial_state: True

  trigger:
  - platform: time
    at: '17:30:00'
    # Triggers at 5.30 pm
  - platform: sun
    event: sunset
    offset: '-1:30:00'
    # Triggers an hour & a half before sunset
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/full'
      # Type "/full" in the no.33 bot

  condition:
    - condition: template
      value_template: >
        {{
        states.input_boolean.disable_sunset.state == 'off' and
        states.group.living_room_lights.state == 'off'
        }}
      # Only fires if the lights are off & the switch is off

  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Full"
      # Activates native Hue 'Full' scene
