- alias: lights_off_morning_inside
  id: lights_off_morning_inside
  initial_state: True

  trigger:
  - platform: time
    at: '08:45:00'

  condition:
    - condition: template
      value_template: >
        {{
        states.input_boolean.disable_work.state == 'off' or
        states.input_boolean.enable_guest.state == 'off' or
        states.binary_sensor.workday_sensor.state == 'on' and
        not is_state('input_select.at_home_today', 'James')
        }}

  action:
    service: homeassistant.turn_off
    entity_id: light.hue_living_room
    data:
      transition: 2

########################

- alias: lights_off_bedtime_inside
  id: lights_off_bedtime_inside
  initial_state: True

  trigger:
  - platform: time
    at: '22:15:00'

  condition:
    - condition: template
      value_template: >
        {{
        states.input_boolean.disable_bedtime.state == 'off' or
        states.input_boolean.enable_guest.state == 'off' or
        states.media_player.plex_shield.state == 'idle'
        }}

  action:
    service: homeassistant.turn_off
    entity_id: light.hue_living_room
    data:
      transition: 2
