- alias: lights_on_night_inside
  initial_state: True

  trigger:
  - platform: state
    entity_id: sensor.motion_hue_living_room
    to: 'on'
    # Triggers if motion detected

  condition:
    condition: and
    conditions:
    - condition: time
      after: "22:30:00"
      before: "05:50:00"
      # Only trigger between 10.30 pm & 5.50 am
    - condition: state
      entity_id: input_boolean.enable_guest
      state: 'off'
      # Don't trigger if you have guests
    - condition: state
      entity_id: group.living_room_lights
      state: 'off'
      # Don't trigger if the lights are on

  action:
    service: light.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Night"
      # Activates native Hue scene 'Night'
