- alias: lights_on_white
  id: lights_on_white
  initial_state: True

  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/white'
      # Type "/white" in the no.33 bot
  - platform: state
    entity_id: input_boolean.enable_white
    to: 'on'

  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "White"
      # Activates native Hue 'White' scene

########################

- alias: lights_on_night
  id: lights_on_night
  initial_state: True

  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/night'
      # Type "/night" in the no.33 bot
  - platform: state
    entity_id: input_boolean.enable_night
    to: 'on'

  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Night"
      # Activates native Hue 'Night' scene

########################

- alias: lights_on_movie
  id: lights_on_movie
  initial_state: True

  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/movie'
      # Type "/morning" in the no.33 bot
  - platform: state
    entity_id: input_boolean.enable_movie
    to: 'on'

  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Movie"
      # Activates native Hue 'Movie' scene
