- alias: input_daily_reset
  initial_state: True

  trigger:
  # - platform: time
  #   after: '02:00:00'
  - platform: time
    at: '02:00:00'


  condition:
    condition: state
    entity_id: input_boolean.enable_guest
    state: 'off'

  action:
    service: homeassistant.turn_on
    entity_id: scene.input_reset
