- alias: input_daily_reset
  id: input_daily_reset
  initial_state: True

  trigger:
  - platform: time
    at: '02:00:00'
    # Triggers at 2 am

  condition:
    condition: state
    entity_id: input_boolean.enable_guest
    state: 'off'
    # Don't trigger if we have guests

  action:
    service: homeassistant.turn_on
    entity_id: scene.input_reset
    # Activates the reset scene
