- alias: input_guest_mode_on
  initial_state: True

  trigger:
  - platform: state
    entity_id: input_boolean.enable_guest
    to: 'on'
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/guest_on'

  action:
  - service: homeassistant.turn_on
    entity_id: scene.input_guests
  - service: homeassistant.turn_on
    entity_id: input_boolean.enable_guest
  - service: notify.get_notified
    data:
      message: 'Automations are off until guest mode has been disabled.'
      title: "Guest Mode Enabled"

########################

- alias: input_guest_mode_off
  initial_state: True

  trigger:
  - platform: state
    entity_id: input_boolean.enable_guest
    to: 'off'
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/guest_off'

  action:
  - service: homeassistant.turn_on
    entity_id: scene.input_reset
  - service: notify.get_notified
    data:
      message: 'Automations have been re-enabled.'
      title: "Guest Mode Disabled"
