- alias: lights_off_morning_outside

  trigger:
    platform: time
    after: '08:40:00'

  action:
    service: homeassistant.turn_off
    entity_id: light.hue_front_porch
    data:
      transition: 2
