- alias: motion_detected
  id: motion_detected
  initial_state: True

  trigger:
  - platform: state
    entity_id:
    - sensor.motion_hue_living_room
    to: 'on'
    # Triggers if motion detected

  condition:
  - condition: state
    entity_id: binary_sensor.presence_james
    state: 'off'
  - condition: state
    entity_id: binary_sensor.presence_gillian
    state: 'off'
    # Only trigger if we are both away

  action:
    service: notify.get_notified
    data:
      message: "Motion Detected"
      title: "Motion has been detected at home"
      # Send a notification
