- alias: notify_tts
  initial_state: True

  trigger:
    platform: state
    entity_id: input_boolean.text_to_speech
    to: 'on'

  action:
  - service: media_player.sonos_snapshot

  - service: tts.google_say
    entity_id: media_player.sonos_all
    data_template:
      message:
        "Hello. The Temperature in the house is

        {{states('sensor.heating_temperature') | round(0) }} degrees C.

        The weather is {{states('sensor.dark_sky_summary')}}.

        {%- if is_state('sensor.james_group', 'is at home') and
               is_state('sensor.gillian_group', 'is at home') -%}

          James & Gillian are both at home.

        {%- else -%}

          James {{states('sensor.james_group')}} & Gillian {{states('sensor.gillian_group')}}.

        {%- endif %}

        Ayteevees shares are worth {{states('sensor.itvl') | round(0)}} pence."

      cache: false

  - delay: '00:00:15'

  - service: media_player.sonos_restore
    # data_template:
    #   entity_id: media_player.sonos_all

  - service: homeassistant.turn_on
    entity_id: scene.input_tts
