- alias: notify_restart
  id: notify_restart
  initial_state: True

  trigger:
  - platform: homeassistant
    event: 'start'
    # Triggers when hass starts up

  action:
  - service: notify.get_notified
    data:
      message: "Home Assistant should now be available"
      title: "Hass Restarted"
      # Sends a notification

########################

- alias: notify_shutdown
  id: notify_shutdown
  initial_state: True

  trigger:
  - platform: homeassistant
    event: 'shutdown'
    # Triggers when hass shuts down

  action:
    service: notify.get_notified
    data:
      message: "Home Assistant is shutting down"
      title: "Hass Shutting Down"
      # Sends a notification

########################

- alias: notify_update
  id: notify_update
  initial_state: True

  trigger:
    platform: state
    entity_id: updater.updater
    # Triggers if hass detects an updated version

  condition:
    condition: template
    value_template: "{{ states('updater.updater') != 'unknown' }}"

  action:
    service: notify.get_notified
    data:
      message: "
      Home Assistant

      {{ states('updater.updater') }}

      is now available. Go to https://home-assistant.io
      "
      title: "Home Assistant Update"
      # Sends a notification
