- alias: notify_restart
  initial_state: True
  trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: homeassistant_start

  action:
    service: notify.get_notified
    data:
      message: "Home Assistant should now be available"
      title: "Home Assistant Restarted"

- alias: notify_update
  initial_state: True
  trigger:
    platform: state
    entity_id: updater.updater

  condition:
    condition: template
    value_template: "{{ states('updater.updater') != 'unknown' }}"

  action:
    service: notify.get_notified
    data:
      message: "Home Assistant {{ states('updater.updater') }} is now available. Go to https://home-assistant.io"
      title: "Home Assistant Update"
