- alias: notify_restart

  trigger:
    platform: homeassistant
    event: start

  action:
    service: notify.get_notified
    data:
      title: "Home Assistant Restarted"
      message: "Home Assistant should now be available"
      target: ""

- alias: notify_update

  trigger:
    platform: state
    entity_id: updater.updater

  condition:
    condition: template
    value_template: "{{ states('updater.updater') != 'unknown' }}"

  action:
    service: notify.get_notified
    data:
      title: "Home Assistant Update"
      message: "Home Assistant {{ states('updater.updater') }} is now available. Go to https://home-assistant.io"
      target: ""
      
