- alias: plex_playing_pauses_sonos
  initial_state: True

  trigger:
  - platform: state
    entity_id:
    - media_player.plex_shield
    - media_player.cast_shield
    to: 'playing'
    # Triggers if watching tv (currently only plex & chromecast supported)

  condition:
    condition: state
    entity_id: media_player.sonos_all
    state: 'playing'
    # Only trigger if music is playing on sonos

  action:
    service: media_player.media_pause
    data:
      entity_id: media_player.sonos_all
      # Pauses all sonos speakers
      # This automation may become redundant if we get a playbase
