- alias: plex_now_playing_movie
  initial_state: True

  trigger:
  - platform: state
    entity_id:
    - media_player.plex_shield
    to: 'playing'
    # Triggers when plex is playing on shield tv

  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.media_player.plex_shield.attributes.media_content_type == "movie" }}'
        # Only trigger if watching a movie
      - condition: or
        conditions:
        - condition: time
          after: "17:30:00"
          # Only trigger after 5.30 pm
        - condition: sun
          after: sunset
          after_offset: "-1:30:00"
          # Or an hour and a half before sunset
        - condition: state
          entity_id: input_boolean.simulate_sunset
          state: 'on'
          # Or if simulate sunset button is "on" (for testing automations)

      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.enable_guest
          state: 'off'
          # Don't trigger if we have guests
        - condition: state
          entity_id: input_boolean.disable_plex
          state: 'off'
          # Don't trigger if disable plex button is "on"

  action:
  - service: homeassistant.turn_on
    entity_id: scene.now_playing_movie
    # Activates now playing scene
  - service: light.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Movie"
      # Activates native Hue scene 'Movie'
