- alias: plex_now_playing_movie
  initial_state: True

  trigger:
  - platform: state
    entity_id:
    - media_player.plex_shield
    to: 'playing'

  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.media_player.plex_shield.attributes.media_content_type == "movie" }}'
      - condition: or
        conditions:
        - condition: time
          after: "17:30:00"
        - condition: sun
          after: sunset
          after_offset: "-1:30:00"
        - condition: state
          entity_id: input_boolean.simulate_sunset
          state: 'on'

      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.enable_guest
          state: 'off'
        - condition: state
          entity_id: input_boolean.disable_plex
          state: 'off'

  action:
  - service: homeassistant.turn_on
    entity_id: scene.now_playing_movie
  - service: light.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Movie"
