- alias: plex_tv_dim_lights
  id: plex_tv_dim_lights
  initial_state: True

  trigger:
  - platform: state
    entity_id:
    - input_boolean.plex_tvshow
    to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_guest
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_plex
        state: 'off'
      - condition: or
        conditions:
          - condition: time
            after: "17:30:00"
          - condition: sun
            after: sunset
            after_offset: "-1:30:00"

  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Dim"
