- alias: plex_movie_lights_dim
  id: plex_movie_lights_full
  initial_state: True

  trigger:
  - platform: state
    entity_id:
    - input_boolean.plex_movie
    to: 'off'
    for:
      seconds: 15

  condition:
  - condition: time
    after: "17:30:00"
  - condition: sun
    after: sunset
    after_offset: "-1:30:00"
  - condition: state
    entity_id: input_boolean.enable_guest
    state: 'off'
  - condition: state
    entity_id: input_boolean.disable_plex
    state: 'off'

  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Dim"
