- alias: Test_Home
  id: test_home
  initial_state: False

  trigger:
  - platform: state
    entity_id:
    - binary_sensor.home_presence
    to: 'on'

  action:
    service: notify.get_notified
    data:
      message: "Test Alert"
      title: "It looks like someone is at home"

###############################################

- alias: Test_Away
  id: test_away
  initial_state: False

  trigger:
  - platform: state
    entity_id:
    - binary_sensor.home_presence
    to: 'off'

  action:
    service: notify.get_notified
    data:
      message: "Test Alert"
      title: "It looks like no-one is at home"
