- alias: Test
  id: test
  initial_state: False

  trigger:
  - platform: state
    entity_id:
    - sensor.plex_shield
    from: '0'

  action:
    service: notify.get_notified
    data:
      message: "Test Alert"
      title: "Monzo account is below £20. Time to top up?"
