###############################
##### NOW PLAYING SCENES ######
###############################

- name: now_playing_movie
  entities:
      input_boolean.plex_movie: on

- name: now_playing_tvshow
  entities:
      input_boolean.plex_tvshow: on

###############################
##### NOW STOPPED SCENES ######
###############################

- name: now_stopped_movie
  entities:
      input_boolean.plex_movie: off

- name: now_stopped_tvshow
  entities:
      input_boolean.plex_tvshow: off
