### Guest scene disables specific automations

- name: 'input_guests'
  entities:
    input_boolean.disable_bedtime:
        state: on
    input_boolean.disable_plex:
        state: on
    input_boolean.disable_work:
        state: on
    input_boolean.simulate_sunset:
        state: off
