###############################
###### BAYESIAN SENSORS #######
####### JAMES PRESENCE ########
###############################

binary_sensor:
  - platform: 'bayesian'
    prior: 0.75
    name: 'Presence James'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.james_oneplus3'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_tado'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_ping'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_oneplus3_blue'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'

###############################
###### BAYESIAN SENSORS #######
###### GILLIAN PRESENCE #######
###############################

  - platform: 'bayesian'
    prior: 0.75
    name: 'Presence Gillian'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.gillian_oneplus_3t'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.gillian_tado'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.gillian_ping'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.gillian_oneplus3t_blue'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'

###############################
###### BAYESIAN SENSORS #######
####### GROUP PRESENCE ########
###############################

group:
  presence:
    name: Presence
    entities:
    - binary_sensor.presence_james
    - binary_sensor.presence_gillian

###############################
####### TEMPLATE SENSORS ######
####  'AT HOME' OR 'AWAY' #####
###############################

sensor:
  - platform: template
    sensors:
      james_home:
        value_template: >
          {% if is_state('binary_sensor.presence_james', 'on') %}
          is at home
          {% else %}
          is away
          {% endif %}
        friendly_name: James

      gillian_home:
        value_template: >
          {% if is_state('binary_sensor.presence_gillian', 'on') %}
          is at home
          {% else %}
          is away
          {% endif %}
        friendly_name: Gillian
