binary_sensor:
  - platform: 'bayesian'
    prior: 0.75
    name: 'James Presence'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.james_tado'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_ping'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_oneplus3'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'

################################

  - platform: 'bayesian'
    prior: 0.75
    name: 'Gillian Presence'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.gillian_tado'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.gillian_ping'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.gillian_oneplus3t'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
