binary_sensor:
  - platform: 'bayesian'
    prior: 0.75
    name: 'James Home'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.james_tado'
        prob_given_true: 0.8
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_ping'
        prob_given_true: 0.8
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_oneplus_3'
        prob_given_true: 0.95
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
