binary_sensor:
  - platform: workday
    country: UK
    # weekdays: sensor "on"
    # weekends or bank holidays: sensor "off"

  - platform: ping
    host: !secret cast_ip
    name: ping_shield
    # Checks if device is "on" or "off"

  - platform: ping
    host: !secret tado_ip
    name: ping_tado

  - platform: ping
    host: !secret hue_ip
    name: ping_hue

  - platform: ping
    host: !secret sonos_ip_1
    name: ping_sonos_1

  - platform: ping
    host: !secret sonos_ip_2
    name: ping_sonos_2

  - platform: ping
    host: !secret sonos_ip_3
    name: ping_sonos_3

  - platform: ping
    host: !secret sony_ip
    name: ping_sony

  - platform: ping
    host: !secret humax_ip
    name: ping_humax

  - platform: ping
    host: !secret synology_ip
    name: ping_synology

  - platform: ping
    host: !secret pihole_ip
    name: ping_pihole

  - platform: template
    sensors:
      james_normal_home_hours:
        entity_id:
          - sensor.time
        value_template: '{{not(strptime("09:00", "%H:%M").time() < now().time() < strptime("18:00", "%H:%M").time())}}'
        friendly_name: James normal home hours

      james_normal_work_hours:
        entity_id:
          - sensor.time
        value_template: '{{(strptime("09:00", "%H:%M").time() < now().time() < strptime("18:00", "%H:%M").time())}}'
        friendly_name: James normal home hours

      dark_outside:
        entity_id:
          - sun.sun
        value_template: "{{states.sun.sun.attributes.elevation|float < 2}}"
        friendly_name: Dark outside

    # Is on for 5 minutes after motion detectors trigger
      # motion_detected:
      #   delay_off:
      #     minutes: 3
      #   entity_id:
      #     - group.motion_detectors
      #   value_template: "{{is_state('group.motion_detectors', 'on')}}"
      #   friendly_name: Motion detected

group:
  binary_sensors:
    name: Online/Offline
    entities:
    - binary_sensor.ping_hue
    - binary_sensor.ping_tado
    - binary_sensor.ping_shield
    - binary_sensor.ping_sonos_1
    - binary_sensor.ping_sonos_2
    - binary_sensor.ping_sonos_3
    - binary_sensor.ping_sony
    - binary_sensor.ping_humax
    - binary_sensor.ping_synology
    - binary_sensor.ping_pihole
    - binary_sensor.ping_james
    - binary_sensor.ping_gillian

  presence:
    name: Presence
    entities:
    - binary_sensor.james_presence
    - binary_sensor.gillian_presence
