sensor:
  - platform: darksky
    api_key: !secret darksky_api
    update_inverval:
      hours: 6
    forecast: 1
    monitored_conditions:
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - summary
    - icon

tado:
  username: !secret tado_user
  password: !secret tado_pass
  #entity_namespace: 'tado'
