###############################
###### DARKSKY WEATHER  #######
###############################

sensor:
  - platform: darksky
    api_key: !secret darksky_api
    update_inverval: '06:00:00'
      #hours: 6
    forecast: 1
    monitored_conditions:
    #- temperature_max
    #- temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - summary
    #- icon

###############################
##### TIME & DATE SENSOR ######
###############################

  - platform: time_date
    display_options:
    - time
    - date

###############################
####### SEASON SENSOR #########
###############################

  - platform: season
