sensor:
  - platform: darksky
    api_key: !secret darksky_api
    update_inverval:
      hours: 6
    forecast: 1
    monitored_conditions:
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - summary
    - icon

  - platform: season

#weather:
#  - platform: metoffice
#    api_key: !secret metoffice

tado:
  username: !secret tado_user
  password: !secret tado_pass

group:
   Tado:
       name: TadoËš
       entities:
       - sensor.heating_heating
       - sensor.heating_humidity
       - sensor.heating_link
       - sensor.heating_overlay
       - sensor.heating_power
       - sensor.heating_tado_mode
       - sensor.heating_temperature
       - sensor.james__gillians_tado_bridge_status
