###############################
###### DARKSKY WEATHER  #######
###############################

# weather:
#   - platform: darksky
#     api_key: !secret darksky_api

sensor:
  - platform: darksky
    api_key: !secret darksky_api
    update_inverval: '06:00:00'
    forecast: 1
    monitored_conditions:
    - apparent_temperature_max
    - apparent_temperature_min
    - summary
    - uv_index

###############################
##### TIME & DATE SENSOR ######
###############################

  - platform: time_date
    display_options:
    - time
    - date

###############################
####### SEASON SENSOR #########
###############################

  - platform: season

###############################
######### TADO SENSOR #########
###############################

tado:
  username: !secret tado_user
  password: !secret tado_pass
