homeassistant:
  customize_domain:
  ### Customize entire domains
    script:
      entity_picture: /local/sw/bobafett.png
    scene:
      entity_picture: /local/sw/jawa.png
    input_boolean:
      entity_picture: /local/sw/thumbs_up.png

  customize_glob:
  ### Customize similar entities
  ### Overrides domain
    "device_tracker.james*":
      entity_picture: /local/sw/anakin.png
    "device_tracker.gillian*":
      entity_picture: /local/sw/hologram.png
    "device_tracker.home*":
      entity_picture: /local/sw/deathstar.png
      hidden: true

    "sensor.james*":
      entity_picture: /local/sw/anakin.png
    "sensor.gillian*":
      entity_picture: /local/sw/hologram.png

    "scene.hue*":
      entity_picture: /local/sw/k2so.png

    "sensor.dark_sky_daily_high_temp*":
      friendly_name: Daily High
    "sensor.dark_sky_daily_high_app*":
      friendly_name: Feels like (high)
    "sensor.dark_sky_daily_low_temp*":
      friendly_name: Daily Low
    "sensor.dark_sky_daily_low_app*":
      friendly_name: Feels like (low)

    "group.all*":
      hidden: false

  customize:
  ### Customize individual entities
  ### Overrides domain & glob
    group.hue_light_scripts:
      control: hidden
      entity_picture: /local/sw/deathstar.png
    group.hue_scripts:
      control: hidden
      entity_picture: /local/sw/deathstar.png
    group.hue_scenes:
      control: hidden
      entity_picture: /local/sw/deathstar.png
    group.james:
      entity_picture: /local/sw/hansolo.png
    group.gillian:
      entity_picture: /local/sw/leia.png
    sensor.james_home:
      entity_picture: /local/sw/hansolo.png
    sensor.gillian_home:
      entity_picture: /local/sw/leia.png

    sensor.heating_temperature:
      friendly_name: Tado˚ Temperature
    sensor.heating_humidity:
      friendly_name: Tado˚ Humidity
    sensor.heating_heating:
      friendly_name: Tado˚ Heating
      entity_picture: /local/Tado/manual.png
    sensor.heating_link:
      friendly_name: Tado˚ Link
    sensor.heating_overlay:
      friendly_name: Tado˚ Overlay
    sensor.heating_power:
      friendly_name: Tado˚ Power
    sensor.heating_tado_mode:
      friendly_name: Tado˚ Mode
    sensor.james__gillians_tado_bridge_status:
      friendly_name: Tado˚ Bridge Status

    sensor.hass:
      icon: mdi:home-assistant
    weblink.homeassistant:
      icon: mdi:home-assistant
    weblink.router:
      icon: mdi:router-wireless

    sensor.motion_hue_living_room:
      friendly_name: Living Room Motion

    binary_sensor.james_presence:
      friendly_name: James (Bayesian)
      entity_picture: /local/sw/poe.png
    binary_sensor.gillian_presence:
      friendly_name: Gillian (Bayesian)
      entity_picture: /local/sw/rey2.png

    scene.hue_dim:
      friendly_name: Dim
    scene.hue_full:
      friendly_name: Full
    scene.hue_movie:
      friendly_name: Movie
    scene.hue_morning:
      friendly_name: Morning
    scene.hue_white:
      friendly_name: White
    scene.hue_night:
      friendly_name: Night
    scene.hue_outside_full:
      friendly_name: Outside Full
    scene.hue_outside_dim:
      friendly_name: Outside Dim
    scene.hue_outside_off:
      friendly_name: Outside Off
    scene.input_guests:
      friendly_name: Guests
    scene.input_reset:
      friendly_name: Reset
    scene.input_after_sunset:
      friendly_name: After Sunset
    scene.now_playing_movie:
      friendly_name: Now Playing Movie
    scene.now_playing_tvshow:
      friendly_name: Now Playing TV

    media_player.kodi_kodi:
      friendly_name: KODI
    media_player.plex_shield:
      friendly_name: PLEX
    media_player.cast_shield:
      friendly_name: CAST
    media_player.universal_tv:
      friendly_name: MEDIA CENTRE

    media_player.sonos_living_room:
      friendly_name: SONOS LIVING ROOM
    media_player.sonos_kitchen:
      friendly_name: SONOS KITCHEN
    media_player.sonos_bedroom:
      friendly_name: SONOS BEDROOM
    media_player.sonos_all:
      friendly_name: SONOS
