homeassistant:
  customize_domain:
  ### Customize entire domains

    script:
      entity_picture: /local/bobafett.png
    scene:
      entity_picture: /local/jawa.png
    input_boolean:
      entity_picture: /local/thumbs.png

  customize_glob:
  ### Customize similar entities
  ### Overrides domain

    "device_tracker.james*":
      entity_picture: /local/anakin.png
    "device_tracker.gillian*":
      entity_picture: /local/hologram.png

    "scene.hue*":
      entity_picture: /local/k2so.png

    "sensor.dark_sky_daily_high_temp*":
      friendly_name: Daily High
    "sensor.dark_sky_daily_high_app*":
      friendly_name: Feels like (high)
    "sensor.dark_sky_daily_low_temp*":
      friendly_name: Daily Low
    "sensor.dark_sky_daily_low_app*":
      friendly_name: Feels like (low)

  customize:
  ### Customize individual entities
  ### Overrides domain & glob
    group.scripts:
      control: hidden
      entity_picture: /local/deathstar.png
    group.james:
      entity_picture: /local/hansolo.png
    group.gillian:
      entity_picture: /local/leia.png

    scene.hue_dim:
      friendly_name: Dim
    scene.hue_full:
      friendly_name: Full
    scene.hue_movie:
      friendly_name: Movie
    scene.hue_morning:
      friendly_name: Morning
    scene.hue_white:
      friendly_name: White
    scene.hue_night:
      friendly_name: Night

    media_player.plex_shield_tv:
      friendly_name: PLEX
    media_player.cast_shield:
      friendly_name: CAST
    media_player.universal_tv:
      friendly_name: MEDIA CENTRE

    media_player.sonos_living_room:
      friendly_name: SONOS LIVING ROOM
    media_player.sonos_kitchen:
      friendly_name: SONOS KITCHEN
    media_player.sonos_bedroom:
      friendly_name: SONOS BEDROOM
    media_player.sonos_all:
      friendly_name: SONOS

    group.today:
      order: 1
    group.tomorrow:
      order: 2
    group.home:
      order: 3
    group.living_room_lights:
      order: 4
    group.outside:
      order: 5
    group.media_centre:
      order: 6
