###############################
##### CUSTOMIZE DOMAINS #######
###############################

homeassistant:
  customize_domain:

    script:
      entity_picture: /local/sw/bobafett.png
    scene:
      entity_picture: /local/sw/jawa.png
    input_boolean:
      entity_picture: /local/sw/thumbs_up.png
    input_select:
      entity_picture: /local/sw/falcon.png

###############################
##### CUSTOMIZE GLOBAL ########
###############################
##### OVERRIDES DOMAINS #######
###############################

  customize_glob:

    "device_tracker.james*":
      entity_picture: /local/sw/anakin.png
    "device_tracker.gillian*":
      entity_picture: /local/sw/hologram.png
    "device_tracker.home*":
      entity_picture: /local/sw/deathstar.png
      hidden: true

    "sensor.james*":
      entity_picture: /local/sw/anakin.png
    "sensor.gillian*":
      entity_picture: /local/sw/hologram.png

    "binary_sensor.ping*":
      device_class: connectivity
    "binary_sensor.presence*":
      device_class: presence

    "scene.hue*":
      entity_picture: /local/sw/k2so.png

    "sensor.dark_sky_daily_high_temp*":
      friendly_name: Daily High
    "sensor.dark_sky_daily_high_app*":
      friendly_name: Feels like (high)
    "sensor.dark_sky_daily_low_temp*":
      friendly_name: Daily Low
    "sensor.dark_sky_daily_low_app*":
      friendly_name: Feels like (low)

    "group.all*":
      hidden: false

###############################
##### CUSTOMIZE ENTITIES ######
###############################
##### OVERRIDES DOMAINS #######
##### OVERRIDES GLOBAL ########
###############################

  customize:
    group.hue_scripts:
      control: hidden
      entity_picture: /local/sw/deathstar.png
    group.hue_scenes:
      control: hidden
      entity_picture: /local/sw/deathstar.png
    group.james:
      entity_picture: /local/sw/hansolo.png
    group.gillian:
      entity_picture: /local/sw/leia.png
    sensor.james_home:
      entity_picture: /local/sw/hansolo.png
    sensor.gillian_home:
      entity_picture: /local/sw/leia.png

    weblink.homeassistant:
      icon: mdi:home-assistant
    weblink.router:
      icon: mdi:router-wireless

    sensor.motion_hue_living_room:
      friendly_name: Living Room Motion

    binary_sensor.presence_james:
      friendly_name: James
      entity_picture: /local/sw/poe.png
    binary_sensor.presence_gillian:
      friendly_name: Gillian
      entity_picture: /local/sw/rey2.png
    binary_sensor.iss:
      entity_picture: /local/sw/falcon.png
      icon: mdi:rocket

    scene.hue_dim:
      friendly_name: Dim
    scene.hue_full:
      friendly_name: Full
    scene.hue_movie:
      friendly_name: Movie
    scene.hue_morning:
      friendly_name: Morning
    scene.hue_white:
      friendly_name: White
    scene.hue_night:
      friendly_name: Night
    scene.hue_outside_full:
      friendly_name: Outside Full
    scene.hue_outside_dim:
      friendly_name: Outside Dim
    scene.hue_outside_off:
      friendly_name: Outside Off
    scene.input_guests:
      friendly_name: Guests
    scene.input_reset:
      friendly_name: Reset
    scene.input_after_sunset:
      friendly_name: After Sunset
    scene.now_playing_movie:
      friendly_name: Now Playing Movie
    scene.now_playing_tvshow:
      friendly_name: Now Playing TV

    media_player.kodi_kodi:
      friendly_name: KODI
    media_player.plex_shield:
      friendly_name: PLEX
    media_player.cast_shield:
      friendly_name: CAST
    media_player.sony_bravia:
      friendly_name: BRAVIA

    media_player.sonos_living_room:
      friendly_name: SONOS LIVING ROOM
    media_player.sonos_kitchen:
      friendly_name: SONOS KITCHEN
    media_player.sonos_bedroom:
      friendly_name: SONOS BEDROOM

    media_player.sonos_living_room_universal:
      friendly_name: SONOS LIVING ROOM
    media_player.sonos_kitchen_universal:
      friendly_name: SONOS KITCHEN
    media_player.sonos_bedroom_universal:
      friendly_name: SONOS BEDROOM

    media_player.sonos_all_universal:
      friendly_name: SONOS

###############################
######## PAGE ORDERS ##########
###############################

    group.default_view:
      order: 1
    group.page_2:
      order: 2
    group.page_3:
      order: 3
    group.page_4:
      order: 4
    group.docker:
      order: 5
    group.page_5:
      order: 6

###############################
####### GROUP ORDERS ##########
###############################

    group.today:
      order: 11
    group.tomorrow:
      order: 12
    group.home:
      order: 13
    group.info:
      order: 14
    group.hue_light_scripts:
      control: hidden
      entity_picture: /local/sw/deathstar.png
      order: 15
    group.living_room_lights:
      order: 16
    group.outside:
      order: 17
    group.media_centre:
      order: 18
