homeassistant:
  customize_domain:
  ### Customize entire domains

    script:
      entity_picture: /local/bobafett.png

    scene:
      entity_picture: /local/jawa.png
      homebridge_hidden: true
    input_boolean:
      entity_picture: /local/thumbs_up.png
      homebridge_hidden: true
    light:
      homebridge_hidden: true
    media_player:
      homebridge_hidden: true

  customize_glob:
  ### Customize similar entities
  ### Overrides domain

    "device_tracker.james*":
      entity_picture: /local/anakin.png
    "device_tracker.gillian*":
      entity_picture: /local/hologram.png

    "sensor.james*":
      entity_picture: /local/anakin.png
    "sensor.gillian*":
      entity_picture: /local/hologram.png

    "scene.hue*":
      entity_picture: /local/k2so.png
      homebridge_hidden: false
    "light.hue*":
      homebridge_hidden: false

    "sensor.dark_sky_daily_high_temp*":
      friendly_name: Daily High
    "sensor.dark_sky_daily_high_app*":
      friendly_name: Feels like (high)
    "sensor.dark_sky_daily_low_temp*":
      friendly_name: Daily Low
    "sensor.dark_sky_daily_low_app*":
      friendly_name: Feels like (low)

  customize:
  ### Customize individual entities
  ### Overrides domain & glob
    group.scripts:
      control: hidden
      entity_picture: /local/deathstar.png
    group.james:
      entity_picture: /local/hansolo.png
    group.gillian:
      entity_picture: /local/leia.png
    sensor.james_group:
      entity_picture: /local/hansolo.png
    sensor.gillian_group:
      entity_picture: /local/leia.png

    sensor.hass:
      entity_picture: /local/kylo_ren.png
    weblink.homeassistant:
      entity_picture: /local/kylo_ren.png

    scene.hue_dim:
      friendly_name: Dim
      homebridge_name: DIM
    scene.hue_full:
      friendly_name: Full
      homebridge_name: FULL
    scene.hue_movie:
      friendly_name: Movie
      homebridge_name: MOVIE
    scene.hue_morning:
      friendly_name: Morning
      homebridge_name: MORNING
    scene.hue_white:
      friendly_name: White
      homebridge_name: WHITE
    scene.hue_night:
      friendly_name: Night
      homebridge_name: NIGHT
    scene.hue_outside_off:
      friendly_name: Outside Off
      homebridge_hidden: true

    input_boolean.enable_guest:
      homebridge_hidden: false
      homebridge_name: GUEST

    media_player.plex_shield_tv:
      friendly_name: PLEX
    media_player.cast_shield:
      friendly_name: CAST
    media_player.universal_tv:
      friendly_name: MEDIA CENTRE

    media_player.sonos_living_room:
      friendly_name: SONOS LIVING ROOM
    media_player.sonos_kitchen:
      friendly_name: SONOS KITCHEN
    media_player.sonos_bedroom:
      friendly_name: SONOS BEDROOM
    media_player.sonos_all:
      friendly_name: SONOS

    group.today:
      order: 1
    group.tomorrow:
      order: 2
    group.home:
      order: 3
    group.living_room_lights:
      order: 4
    group.outside:
      order: 5
    group.media_centre:
      order: 6

    light.hue_garage:
      hidden: true
      homebridge_hidden: true
    light.hue_outside:
      hidden: true
      homebridge_hidden: true
    light.hue_living_room:
      hidden: true
      homebridge_hidden: true
    light.hue_all:
      hidden: true
      homebridge_hidden: true
    light.hue_hue_white_lamp_2:
      hidden: true
      homebridge_hidden: true
    light.hue_hue_white_lamp_3:
      hidden: true
      homebridge_hidden: true
