###############################
########### HUE HUB ###########
###############################

hue:
  bridges:
    - host: !secret hue_ip
      #entity_namespace: 'hue'
      filename: phue.conf
      allow_unreachable: true
      allow_hue_groups: true

###############################
########## HUE SENSORS ########
###############################

sensor:
  - platform: hue
    # Custom component allows hue motion & hue tap sensors

  - platform: template
    sensors:
      living_room_temp:
        friendly_name: Living Room Temp
        value_template: >
          {{ states.sensor.motion_hue_living_room.attributes.temperature }}
        unit_of_measurement: "°C"
        # Creates a sensor to display living room temperature

      motion_sensor_battery:
        friendly_name: Motion Sensor Battery
        value_template: >
          {{ states.sensor.motion_hue_living_room.attributes.battery }}
        unit_of_measurement: "%"
        # Creates a sensor to display the motion sensor battery

###############################
########## HUE GROUPS #########
###############################

group:
  outside:
      name: Outside
      entities:
      - light.hue_front_porch
      #- light.front_porch

  living_room_lights:
      name: Living Room Lights
      entities:
      - light.hue_big_floor_lamp
      - light.hue_small_floor_lamp
      - light.hue_table_lamp
      - light.hue_tv_backlight
      #- light.big_floor_lamp
      #- light.small_floor_lamp
      #- light.table_lamp
      #- light.tv_backlight

  hue_light_scripts:
      name: Hue Lights
      entities:
      - group.hue_scripts

  hue_scripts:
      name: Hue Scripts
      entities:
      - script.hue_dim
      - script.hue_full
      - script.hue_movie
      - script.hue_morning
      - script.hue_white
      - script.hue_night
      - script.hue_outside_full
      - script.hue_outside_dim

  # hue_scenes:
  #     name: Hue Scenes
  #     entities:
  #     - scene.hue_dim
  #     - scene.hue_full
  #     - scene.hue_movie
  #     - scene.hue_morning
  #     - scene.hue_white
  #     - scene.hue_night
  #     - scene.hue_outside_full
  #     - scene.hue_outside_dim
