light:
  - platform: hue
    entity_namespace: 'hue'
    host: !secret hue_ip
    allow_unreachable: true
    allow_hue_groups: true

hue:

sensor:
  - platform: hue
    # Custom component allows hue motion & hue tap sensors

group:
  outside:
      name: Outside
      entities:
      - light.hue_front_porch

  living_room_lights:
      name: Living Room Lights
      entities:
      - light.hue_big_floor_lamp
      - light.hue_small_floor_lamp
      - light.hue_table_lamp
      - light.hue_tv_backlight
