script:
  hue_dim:
    alias: Dim
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dim"

  hue_full:
    alias: Full
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Full"

  hue_morning:
    alias: Morning
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dim"

  hue_movie:
    alias: Movie
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Movie"

  hue_night:
    alias: Night
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Night"

  hue_white:
    alias: White
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "White"

group:
  scripts:
      name: Scripts
      entities:
      - script.hue_dim
      - script.hue_full
      - script.hue_movie
      - script.hue_morning
      - script.hue_white
      - script.hue_night

  scenes:
      name: Scenes
      entities:
      - scene.hue_dim
      - scene.hue_full
      - scene.hue_movie
      - scene.hue_morning
      - scene.hue_white
      - scene.hue_night

homeassistant:
  customize:
    group.scripts:
      control: hidden
      entity_picture: /local/tie.png

    scene.hue_dim:
      friendly_name: Dim
    scene.hue_full:
      friendly_name: Full
    scene.hue_movie:
      friendly_name: Movie
    scene.hue_morning:
      friendly_name: Morning
    scene.hue_white:
      friendly_name: White
    scene.hue_night:
      friendly_name: Night

  customize_domain:
    script:
      entity_picture: /local/bobafett.png
    scene:
      entity_picture: /local/jawa.png

  customize_glob:
    "scene.hue*":
      entity_picture: /local/k2so.png
