notify:
  - platform: pushover
    name: 'Pushover'
    api_key: !secret pushover_api
    user_key: !secret pushover_user

  # - platform: slack
  #   name: 'Slack'
  #   api_key: !secret slack_api
  #   default_channel: 'home-assistant'
  #   icon: ':rocket:'
  #   username: 'home-assistant'

  - platform: group
    name: 'get_notified'
    services:
      #- service: slack
      #- service: nfandroidtv
      - service: pushover
