###############################
########## PAGE -1- ###########
###############################

group:
  default_view:
    name: Home
    view: true
    entities:
      - group.today
      - group.tomorrow
      - group.buses
      - group.home
      - group.info
      - group.living_room_lights
      - group.outside
      - group.hue_light_scripts
      - group.media_centre

###############################
########## PAGE -3- ###########
###############################

  Page_3:
    name: Page 3
    view: true
    entities:
      - group.web
      - group.other_scenes
      - group.hue_scripts
      - group.hue_scenes

###############################
########## PAGE -4- ###########
###############################

  Page_4:
    name: Page 4
    view: true
    entities:
      - group.guest
      - group.bedtime
      - group.overrides
      - group.now_playing
      - group.sunset

###############################
########## PAGE -5- ###########
###############################

  Page_5:
    name: ALL
    view: true
    entities:
      - group.today
      - group.tomorrow
      - group.home
      - group.james
      - group.gillian
      - group.living_room_lights
      - group.outside
      - media_player.plex_shield
      - media_player.cast_shield
      - media_player.kodi_kodi
      - media_player.sonos_all_universal
      - group.guest
      - group.overrides
      - group.all_devices
      - group.all_automations
      - group.all_lights
      - group.all_scripts
      - group.binary_sensors

###############################
######### MISC GROUPS #########
###############################

  today:
      name: Today
      entities:
      - sensor.time
      - sensor.date
      - weather.dark_sky
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.season
      - sun.sun

  buses:
      name: Buses
      control: hidden
      entities:
      - sensor.next_bus_to_leeds
      - sensor.next_bus_to_keighley
      - sensor.next_bus_to_work_scheduled
      - sensor.next_bus_home_scheduled

  tomorrow:
      name: Tomorrow
      entities:
      - sensor.dark_sky_daily_high_apparent_temperature_1
      - sensor.dark_sky_daily_low_apparent_temperature_1

  home:
      name: Home
      control: hidden
      entities:
      - sensor.james_home
      - sensor.gillian_home
      - binary_sensor.presence_james
      - binary_sensor.presence_gillian
      - input_boolean.enable_guest

  info:
      name: Info
      control: hidden
      entities:
      - sensor.tado_heating_mode
      - sensor.tado_heating_temperature
      - sensor.living_room_temp
      - sensor.motion_hue_living_room
      - sensor.hue_tap
      - sensor.motion_sensor_battery
      - input_boolean.restart_hass_dockermon
      #- script.restart_hass
      #- input_select.at_home_today

  other_scenes:
      name: Other Scenes
      entities:
      - scene.input_after_sunset
      - scene.input_guests
      - scene.input_reset
      - scene.now_playing_movie
      - scene.now_playing_tvshow
