group:
  james:
      name: James
      entities:
      - device_tracker.james_oneplus3
      - device_tracker.james_tado
      - device_tracker.james_ping

  gillian:
      name: Gillian
      entities:
      - device_tracker.gillian_oneplus3t
      - device_tracker.gillian_tado
      - device_tracker.gillian_ping

  home:
      name: Home
      control: hidden
      entities:
      - sensor.james_home
      - sensor.gillian_home
      - sensor.heating_temperature
      - sensor.heating_humidity
      - sensor.living_room_temp
      - sensor.motion_hue_living_room
      - sensor.hue_tap
      - sensor.motion_sensor_battery
      - input_boolean.enable_guest
      - input_select.at_home_today
