group:
  james:
      name: 'James'
      entities:
      - device_tracker.james
      - device_tracker.james_tado

  gillian:
      name: 'Gillian'
      entities:
      - device_tracker.gillian
      - device_tracker.gillian_tado

  home:
      name: 'Home'
      entities:
      - group.james
      - group.gillian

homeassistant:
  customize:
    - entity_id: group.james
      friendly_name: 'James'
      entity_picture: /local/james.png

    - entity_id: device_tracker.james*
      entity_picture: /local/james.png

    - entity_id: group.gillian
      friendly_name: 'Gillian'
      entity_picture: /local/gillian.jpg

    - entity_id: device_tracker.gillian*
      entity_picture: /local/gillian.jpg

# homeassistant:
#   customize_glob:
#    - 'device_tracker.james*':
#        entity_picture: /local/james.png
#    - 'device_tracker.gillian*':
#        entity_picture: /local/gillian.jpg

#   customize:
#    - group.james:
#         friendly_name: 'James'
#         entity_picture: /local/james.png
#    - group.gillian:
#         friendly_name: 'Gillian'
#         entity_picture: /local/gillian.jpg
