media_player:
  - platform: plex
    entity_namespace: 'plex'

  - platform: cast
    entity_namespace: 'cast'
    host: !secret cast_ip

  - platform: universal
    name: 'universal_tv'
    children:
       - media_player.plex_shield
       - media_player.cast_shield

group:
  media_centre:
      name: Media Centre
      entities:
      - media_player.plex_shield
      - media_player.sonos_all

  media_players:
      name: Media Players
      entities:
      - media_player.plex_shield
      - media_player.cast_shield
      - media_player.sonos_living_room
      - media_player.sonos_kitchen
      - media_player.sonos_bedroom
      - media_player.universal_tv
      - media_player.sonos_all

  now_playing:
      name: Now Playing
      control: hidden
      entities:
      - input_boolean.plex_movie
      - input_boolean.plex_tvshow
