media_player:
  - platform: plex
    entity_namespace: 'plex'
    ssl: true
    include_non_clients: true
    scan_interval: 10

  - platform: cast
    entity_namespace: 'cast'
    host: !secret cast_ip

  - platform: kodi
    entity_namespace: 'kodi'
    host: !secret cast_ip
    port: 8033

  - platform: universal
    name: 'universal_tv'
    children:
       - media_player.plex_shield
       - media_player.cast_shield

sensor:
  - platform: plex
    name: plex_shield
    host: !secret plex_ip
    port: !secret plex_port

group:
  media_centre:
      name: Media Centre
      entities:
      - media_player.plex_shield
      - media_player.sonos_all

  media_players:
      name: Media Players
      entities:
      - media_player.plex_shield
      - media_player.kodi_kodi
      - media_player.cast_shield
      - media_player.sonos_living_room
      - media_player.sonos_kitchen
      - media_player.sonos_bedroom
      - media_player.universal_tv
      - media_player.sonos_all

  now_playing:
      name: Now Playing
      control: hidden
      entities:
      - input_boolean.plex_movie
      - input_boolean.plex_tvshow
