homeassistant:
  customize_domain:
    scene:
      homebridge_hidden: true
      entity_picture: /local/jawa.png


  customize_glob:
    "scene.hue*":
      homebridge_hidden: false
      entity_picture: /local/k2so.png
