media_player:
  - platform: sonos
    entity_namespace: 'sonos'
    hosts:
      - !secret sonos_ip_1
      - !secret sonos_ip_2
      - !secret sonos_ip_3

  - platform: universal
    name: sonos_all
    children:
       - media_player.sonos_living_room
       - media_player.sonos_kitchen
       - media_player.sonos_bedroom

homeassistant:
  customize:
    media_player.sonos_living_room:
      friendly_name: SONOS LIVING ROOM

    media_player.sonos_kitchen:
      friendly_name: SONOS KITCHEN

    media_player.sonos_bedroom:
      friendly_name: SONOS BEDROOM

    media_player.sonos_all:
      friendly_name: SONOS
