media_player:
  - platform: sonos
    entity_namespace: 'sonos'
    hosts:
      - !secret sonos_ip_1
      - !secret sonos_ip_2
      - !secret sonos_ip_3

  - platform: universal
    name: 'sonos_all'
    children:
       - media_player.sonos_living_room
       - media_player.sonos_kitchen
       - media_player.sonos_bedroom

homeassistant:
  customize:
    - entity_id: media_player.sonos*
      hidden: true
      homebridge_hidden: true

    - entity_id: media_player.sonos_living_room
      friendly_name: 'SONOS LIVING ROOM'
      homebridge_name: 'Living Room Speakers'
      hidden: false
      homebridge_hidden: true

    - entity_id: media_player.sonos_kitchen
      friendly_name: 'SONOS KITCHEN'
      homebridge_name: 'Kitchen Speakers'
      hidden: false
      homebridge_hidden: true

    - entity_id: media_player.sonos_bedroom
      friendly_name: 'SONOS BEDROOM'
      homebridge_name: 'Bedroom Speakers'
      hidden: false
      homebridge_hidden: true

    - entity_id: media_player.sonos_all
      friendly_name: 'SONOS ALL'
      homebridge_name: 'All Speakers'
      hidden: false
      homebridge_hidden: true
