sensor:
  - platform: template
    sensors:
      james_group:
        value_template:
          "{% if is_state('binary_sensor.james_home', 'on') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: James

  - platform: template
    sensors:
      gillian_group:
        value_template:
          "{% if is_state('binary_sensor.gillian_home', 'on') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: Gillian
