sensor:
  - platform: template
    sensors:
      james_home:
        value_template:
          "{% if is_state('binary_sensor.james_presence', 'on') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: James

      gillian_home:
        value_template:
          "{% if is_state('binary_sensor.gillian_presence', 'on') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: Gillian
