sensor:
  - platform: template
    sensors:
      james_group:
        value_template:
          "{% if is_state('group.james', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: James

  - platform: template
    sensors:
      james_tado:
        value_template:
          "{% if is_state('device_tracker.james_tado', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      james_oneplus3:
        value_template:
          "{% if is_state('device_tracker.james_oneplus3', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      gillian_group:
        value_template:
          "{% if is_state('group.gillian', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: Gillian

  - platform: template
    sensors:
      gillian_tado:
        value_template:
          "{% if is_state('device_tracker.gillian_tado', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      gillian_oneplus3:
        value_template:
          "{% if is_state('device_tracker.gillian_oneplus3', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"
