sensor:
  - platform: template
    sensors:
      james_group:
        value_template:
          "{% if is_state('group.james', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: James

  - platform: template
    sensors:
      gillian_group:
        value_template:
          "{% if is_state('group.gillian', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"
        friendly_name: Gillian
