zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 150
    icon: mdi:home-map-marker

  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 150
    icon: mdi:account-multiple

device_tracker:
  - platform: ping
    hosts:
      james_ping: !secret james_ip
      gillian_ping: !secret gillian_ip

  - platform: tado
    username: !secret tado_user
    password: !secret tado_pass
    home_id: !secret home_id

  - platform: nmap_tracker
    hosts:
      - !secret james_ip
      - !secret gillian_ip

#  - platform: asuswrt
#    host: !secret asus_ip
#    username: !secret asus_username
#    password: !secret asus_password

    consider_home: 0:03:00
    interval_seconds: 0:03:00
    track_new_devices: true

binary_sensor:
  - platform: 'bayesian'
    prior: 0.75
    name: 'James Home'
    probability_threshold: 0.95
    observations:
      - entity_id: 'device_tracker.james_tado'
        prob_given_true: 0.8
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_ping'
        prob_given_true: 0.99
        prob_given_false: 0.10
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.james_oneplus_3'
        prob_given_true: 0.95
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'