###############################
####### ZONES SENSOR ##########
###############################

zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 150
    icon: mdi:home-map-marker

  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 150
    icon: mdi:account-multiple

###############################
###### DEVICE TRACKERS ########
###############################

device_tracker:
############ PING #############
  - platform: ping
    count: 5
    hosts:
      james_ping: !secret james_ip
      gillian_ping: !secret gillian_ip
    consider_home: 0:05:00
    interval_seconds: 0:02:00
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

########## BLUETOOTH ##########
  - platform: bluetooth_tracker

############ TADO #############
  - platform: tado
    username: !secret tado_user
    password: !secret tado_pass
    home_id: !secret home_id

############ ASUS #############
  - platform: asuswrt
    host: !secret asus_ip
    username: !secret asus_username
    password: !secret asus_password
    protocol: ssh
    port: 32

###############################
###### TRACKING GROUPS ########
###############################

group:
  james:
      name: James
      entities:
      - device_tracker.james_oneplus3_blue
      - device_tracker.james_tado
      - device_tracker.james_ping
      - device_tracker.james_oneplus3

  gillian:
      name: Gillian
      entities:
      - device_tracker.gillian_oneplus3t_blue
      - device_tracker.gillian_tado
      - device_tracker.gillian_ping
      - device_tracker.gillian_oneplus_3t
