sensor:
  - platform: darksky
    api_key: !secret darksky_api
    update_inverval:
      hours: 6
    forecast: 1
    monitored_conditions:
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - summary
    - icon

homeassistant:
  customize_glob:
    sensor.dark_sky*:
      homebridge_hidden: true

    sensor.dark_sky_daily_high_temp*:
      friendly_name: Daily High

    sensor.dark_sky_daily_high_app*:
      friendly_name: Feels like (high)

    sensor.dark_sky_daily_low_temp*:
      friendly_name: Daily Low

    sensor.dark_sky_daily_low_app*:
      friendly_name: Feels like (low)
