weblink:
  entities:
    - name: homeassistant
      url: https://home-assistant.io
    - name: Router
      url: https://192.168.179.1:8443/index.asp

# sensor:
#   - platform: scrape
#     resource: https://home-assistant.io
#     select: ".current-version h1"
#     name: hass

#  - platform: yahoo_finance
#    symbols:
#      - ITV.L

sensor:
  - platform: monzo
    client_id: !secret monzo_client_id
    client_secret: !secret monzo_client_secret
    name: 'Monzo'
    #cache_path: '/.homeassistant/cache'
