weblink:
  entities:
    - name: homeassistant
      url: https://home-assistant.io
    - name: Router
      url: https://192.168.179.1:8443/index.asp

sensor:
  - platform: monzo
    client_id: !secret monzo_client_id
    client_secret: !secret monzo_client_secret
    name: 'Monzo'
    current_account: true
    #cache_path: '/.homeassistant/cache'
