### HOME ASSISTANT ###
###  BASIC CONFIG  ###

homeassistant:
  name: No. 33
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Europe/London
  packages: !include_dir_named includes/packages

### ADDITIONAL CONFIG ###

#introduction:
#discovery:
#ios:
#emulated_hue:
  #listen_port: 80
updater:
config:
sun:
conversation:
shopping_list:
history:
logger:
  default: error

recorder:
  purge_days: 10
  exclude:
    domains:
    - sun
    - sensor

logbook:
  exclude:
    domains:
    - sun
    - sensor
    - device_tracker

http:
  api_password: !secret http_password
  trusted_networks:
    - !secret trusted_ip_1
    - !secret trusted_ip_2
    - !secret trusted_ip_3
  ip_ban_enabled: true
  login_attempts_threshold: 5
#
### INCLUDE FURTHER CONFIG FILES ###
#
automation: !include_dir_merge_list includes/automation
scene: !include_dir_merge_list includes/scene
