###############################
####### HOME ASSISTANT ########
######## BASIC CONFIG #########
###############################

homeassistant:
  name: No. 33
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Europe/London
  packages: !include_dir_named includes/packages

###############################
##### ADDITIONAL CONFIG #######
###############################

#introduction:
#discovery:
updater:
config:
sun:
conversation:
shopping_list:
map:
history:
logger:
  default: error

recorder:
  purge_interval: 5
  purge_keep_days: 2
  exclude:
    domains:
    - sun
    - sensor

logbook:
  exclude:
    domains:
    - sun
    - sensor
    - device_tracker
    entities:
    - group.info

http:
  api_password: !secret http_password
  trusted_networks:
    - !secret trusted_ip_1
    - !secret trusted_ip_2
    - !secret trusted_ip_3
  ip_ban_enabled: true
  login_attempts_threshold: 5

homekit:
  pincode: !secret homekit_pincode

###############################
####### INCLUDE FURTHER #######
######## CONFIG FILES #########
###############################

automation: !include_dir_merge_list includes/automation
scene: !include_dir_merge_list includes/scene
script: !include_dir_merge_named includes/script/
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named includes/themes/
